### ISSUE TITLE
大佬，能否再完善下？

### ISSUE THREAD

**Issue by buzhongbuyi** [fangzhengjin/PanelTabs#1]
1.Tab项标题国际化怎么处理？
2.Tab个数超过屏幕怎么处理？

**Comment by fangzhengjin** [comment]
> 1.Tab项标题国际化怎么处理？ 2.Tab个数超过屏幕怎么处理？

1. 标签国际化, 标签的title实质是取的路由名称, 你把路由国际化后, 新开的标签就是国际化后的名称了, 切换国际化可以吧当前所有打开的页面全部关闭, 这样可以保证打开的标签名称和国际化一致
2. 关于个数的限制  我节后看一下~

**Comment by fangzhengjin** [comment]
tab个数超限提示及tab超出可视范围可滚动问题, 已在 [umi-plugin-panel-tabs](https://github.com/fangzhengjin/umi-plugin-panel-tabs) 的 0.0.11 版本发布
